/*
 * x l S Q L  
 * (c) daichangya, xlsql.jsdiff.com
 * See XLSQL-license.txt for license details
 *
 */
package com.jsdiff.xlsql.jdbc;

import java.io.InputStream;
import java.io.Reader;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;

import com.jsdiff.xlsql.database.sql.ICommand;

/**
 * xlPreparedStatement - xlSQL预编译语句实现
 * 
 * <p>该类实现了JDBC PreparedStatement接口，作为后端数据库预编译语句的包装器。
 * 在执行预编译语句时会先通过xlSQL解析器解析，然后执行相应的命令。</p>
 * 
 * @author daichangya
 */
public class xlPreparedStatement extends xlStatement implements PreparedStatement {

    private String psql;
    private PreparedStatement dbPstm;
    
    //~ Constructors �����������������������������������������������������������

    /**
     * 创建预编译语句实例
     * 
     * @param con 关联的xlConnection对象
     * @param pstm 后端数据库的PreparedStatement对象
     * @param sql 预编译的SQL语句
     * @throws SQLException 如果创建失败则抛出异常
     */
    protected xlPreparedStatement(xlConnection con, PreparedStatement pstm, 
                                             String sql) throws SQLException {
        super(con,pstm);
        dbPstm = pstm;
        psql = sql;
    }

    //~ Methods ����������������������������������������������������������������

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#addBatch
    */
    public void addBatch() throws SQLException {
        dbPstm.addBatch();
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#clearParameters
    */
    public void clearParameters() throws SQLException {
        dbPstm.clearParameters();
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#execute
    */
    public boolean execute() throws SQLException {
        boolean ret;
        // 解析SQL语句为xlSQL命令对象
        ICommand cmd = xlCon.xlsql.parseSql(psql);        
        if (cmd.execAllowed()) {
            // 执行后端数据库的预编译语句（可能抛出SQLException，传递给客户端）
            ret = dbPstm.execute();
            // 执行xlSQL命令
            cmd.execute();
        }
        else {
            throw new SQLException("XLSQL: execute not allowed");
        }
        return ret;
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#execute
    */
    public boolean execute(String sql, int autoGeneratedKeys)
                    throws SQLException {
        boolean ret;
        ICommand cmd = xlCon.xlsql.parseSql(sql);        
        if (cmd.execAllowed()) {
            // dbStm may throw an SQLException..., pass on to client
            ret = dbPstm.execute(sql);
            cmd.execute();
        }
        else {
            throw new SQLException("XLSQL: execute not allowed");
        }
        return ret;
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#executeQuery
    */
    public ResultSet executeQuery() throws SQLException {
        ResultSet ret = dbPstm.executeQuery();
        return ret;
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#executeUpdate
    */
    public int executeUpdate() throws SQLException {
        int ret;
        ICommand cmd = xlCon.xlsql.parseSql(psql); 
        if (cmd.execAllowed()) {
            // dbStm may throw an SQLException..., pass on to client
            ret = dbPstm.executeUpdate(psql);
            cmd.execute();
        }
        else {
            throw new SQLException("XLSQL: execute not allowed");
        }
        return ret;
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#getMetaData
    */
    public ResultSetMetaData getMetaData() throws SQLException {
        return dbPstm.getMetaData();
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#getParameterMetaData
    */
    public ParameterMetaData getParameterMetaData() throws SQLException {
        ParameterMetaData dbPsMeta = dbPstm.getParameterMetaData();
        ParameterMetaData psMeta = new xlParameterMetaData(this, dbPsMeta);
        return psMeta;
    }

    @Override
    public void setRowId(int parameterIndex, RowId x) throws SQLException {

    }

    @Override
    public void setNString(int parameterIndex, String value) throws SQLException {

    }

    @Override
    public void setNCharacterStream(int parameterIndex, Reader value, long length) throws SQLException {

    }

    @Override
    public void setNClob(int parameterIndex, NClob value) throws SQLException {

    }

    @Override
    public void setClob(int parameterIndex, Reader reader, long length) throws SQLException {

    }

    @Override
    public void setBlob(int parameterIndex, InputStream inputStream, long length) throws SQLException {

    }

    @Override
    public void setNClob(int parameterIndex, Reader reader, long length) throws SQLException {

    }

    @Override
    public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException {

    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setArray
    */
    public void setArray(int i, Array x) throws SQLException {
        dbPstm.setArray(i, x);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setAsciiStream
    */
    public void setAsciiStream(int parameterIndex, java.io.InputStream x, 
                               int length) throws SQLException {
        dbPstm.setAsciiStream(parameterIndex, x, length);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setBigDecimal
    */
    public void setBigDecimal(int parameterIndex, java.math.BigDecimal x)
                       throws SQLException {
        dbPstm.setBigDecimal(parameterIndex, x);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setBinaryStream
    */
    public void setBinaryStream(int parameterIndex, java.io.InputStream x, 
                                int length) throws SQLException {
        dbPstm.setBinaryStream(parameterIndex, x, length);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setBlob
    */
    public void setBlob(int i, Blob x) throws SQLException {
        dbPstm.setBlob(i, x);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setBoolean
    */
    public void setBoolean(int parameterIndex, boolean x)
                    throws SQLException {
        dbPstm.setBoolean(parameterIndex, x);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setByte
    */
    public void setByte(int parameterIndex, byte x) throws SQLException {
        dbPstm.setByte(parameterIndex, x);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setBytes
    */
    public void setBytes(int parameterIndex, byte[] x)
                  throws SQLException {
        dbPstm.setBytes(parameterIndex, x);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setCharacterStream
    */
    public void setCharacterStream(int parameterIndex, java.io.Reader reader, 
                                   int length) throws SQLException {
        dbPstm.setCharacterStream(parameterIndex, reader, length);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setClob
    */
    public void setClob(int i, Clob x) throws SQLException {
        dbPstm.setClob(i, x);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setCursorName
    */
    public void setCursorName(String name) throws SQLException {
        dbPstm.setCursorName(name);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setDate
    */
    public void setDate(int parameterIndex, Date x)
                 throws SQLException {
        dbPstm.setDate(parameterIndex, x);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setDate
    */
    public void setDate(int parameterIndex, Date x, 
                        java.util.Calendar cal) throws SQLException {
        dbPstm.setDate(parameterIndex, x, cal);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setDouble
    */
    public void setDouble(int parameterIndex, double x)
                   throws SQLException {
        dbPstm.setDouble(parameterIndex, x);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setFloat
    */
    public void setFloat(int parameterIndex, float x) throws SQLException {
        dbPstm.setFloat(parameterIndex, x);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setInt
    */
    public void setInt(int parameterIndex, int x) throws SQLException {
        dbPstm.setInt(parameterIndex, x);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setLong
    */
    public void setLong(int parameterIndex, long x) throws SQLException {
         dbPstm.setLong(parameterIndex, x);
   }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setNull
    */
    public void setNull(int parameterIndex, int sqlType)
                 throws SQLException {
        dbPstm.setNull(parameterIndex, sqlType);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setNull
    */
    public void setNull(int paramIndex, int sqlType, String typeName)
                 throws SQLException {
        dbPstm.setNull(paramIndex, sqlType, typeName);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setObject
    */
    public void setObject(int parameterIndex, Object x)
                   throws SQLException {
        dbPstm.setObject(parameterIndex, x);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setObject
    */
    public void setObject(int parameterIndex, Object x, int targetSqlType)
                   throws SQLException {
        dbPstm.setObject(parameterIndex, x, targetSqlType);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setObject
    */
    public void setObject(int parameterIndex, Object x, int targetSqlType, 
                          int scale) throws SQLException {
        dbPstm.setObject(parameterIndex, x, targetSqlType);
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x, long length) throws SQLException {

    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x, long length) throws SQLException {

    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader, long length) throws SQLException {

    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException {

    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException {

    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader) throws SQLException {

    }

    @Override
    public void setNCharacterStream(int parameterIndex, Reader value) throws SQLException {

    }

    @Override
    public void setClob(int parameterIndex, Reader reader) throws SQLException {

    }

    @Override
    public void setBlob(int parameterIndex, InputStream inputStream) throws SQLException {

    }

    @Override
    public void setNClob(int parameterIndex, Reader reader) throws SQLException {

    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setRef
    */
    public void setRef(int i, Ref x) throws SQLException {
        dbPstm.setRef(i, x);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setShort
    */
    public void setShort(int parameterIndex, short x) throws SQLException {
        dbPstm.setShort(parameterIndex, x);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setString
    */
    public void setString(int parameterIndex, String x)
                   throws SQLException {
        dbPstm.setString(parameterIndex, x);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setTime
    */
    public void setTime(int parameterIndex, Time x)
                 throws SQLException {
        dbPstm.setTime(parameterIndex, x);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setTime
    */
    public void setTime(int parameterIndex, Time x, 
                        java.util.Calendar cal) throws SQLException {
        dbPstm.setTime(parameterIndex, x, cal);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setTimestamp
    */
    public void setTimestamp(int parameterIndex, Timestamp x)
                      throws SQLException {
        dbPstm.setTimestamp(parameterIndex, x);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setTimestamp
    */
    public void setTimestamp(int parameterIndex, Timestamp x, 
                             java.util.Calendar cal) throws SQLException {
        dbPstm.setTimestamp(parameterIndex, x, cal);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setURL
    */
    public void setURL(int parameterIndex, java.net.URL x)
                throws SQLException {
        dbPstm.setURL(parameterIndex, x);
    }

    /**
    * Implements method in interface java.sql.PreparedStatement
    * @see PreparedStatement#setUnicodeStream
    */
    public void setUnicodeStream(int parameterIndex, java.io.InputStream x, 
                                 int length) throws SQLException {
        dbPstm.setUnicodeStream(parameterIndex, x, length);
    }
}